#!/usr/bin/env python3

import os
from pathlib import Path

CONTENT_DIR = Path.home() / "codebase" / "my" / "iany.me" / "content"

for root, dirs, files in os.walk('.')
    print(root, "consumes", end=" ")
    print(sum(getsize(join(root, name)) for name in files), end=" ")
    print("bytes in", len(files), "non-directory files")
    if 'CVS' in dirs:
        dirs.remove('CVS')  # don't visit CVS directories
